// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "jni.h"
#include "dartjni.h"

thread_local JNIEnv *jniEnv;
JniContext *jni;

JniContext *(*context_getter)(void);
JNIEnv *(*env_getter)(void);

void setJniGetters(JniContext *(*cg)(void),
        JNIEnv *(*eg)(void)) {
    context_getter = cg;
    env_getter = eg;
}

// ao.marco_domingos.scanner_api_example.Scanner
jclass _c_Scanner = NULL;

jmethodID _m_Scanner__ctor = NULL;
FFI_PLUGIN_EXPORT
JniResult Scanner__ctor() {
    load_env();
        load_class_global_ref(&_c_Scanner, "ao/marco_domingos/scanner_api_example/Scanner");
    if (_c_Scanner == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Scanner,
      &_m_Scanner__ctor, "<init>", "()V");
    if (_m_Scanner__ctor == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Scanner, _m_Scanner__ctor);
    return to_global_ref_result(_result);
}

jmethodID _m_Scanner__getCode = NULL;
FFI_PLUGIN_EXPORT
JniResult Scanner__getCode(jobject self_,jobject context,jobject continuation) {
    load_env();
        load_class_global_ref(&_c_Scanner, "ao/marco_domingos/scanner_api_example/Scanner");
    if (_c_Scanner == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Scanner,
      &_m_Scanner__getCode, "getCode", "(Landroid/content/Context;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;");
    if (_m_Scanner__getCode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Scanner__getCode, context, continuation);
    return to_global_ref_result(_result);
}

jmethodID _m_Scanner__await0 = NULL;
FFI_PLUGIN_EXPORT
JniResult Scanner__await0(jobject self_,jobject task,jobject continuation) {
    load_env();
        load_class_global_ref(&_c_Scanner, "ao/marco_domingos/scanner_api_example/Scanner");
    if (_c_Scanner == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Scanner,
      &_m_Scanner__await0, "await", "(Lcom/google/android/gms/tasks/Task;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;");
    if (_m_Scanner__await0 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Scanner__await0, task, continuation);
    return to_global_ref_result(_result);
}

// com.google.mlkit.vision.codescanner.GmsBarcodeScanning
jclass _c_GmsBarcodeScanning = NULL;

jmethodID _m_GmsBarcodeScanning__getClient = NULL;
FFI_PLUGIN_EXPORT
JniResult GmsBarcodeScanning__getClient(jobject context) {
    load_env();
        load_class_global_ref(&_c_GmsBarcodeScanning, "com/google/mlkit/vision/codescanner/GmsBarcodeScanning");
    if (_c_GmsBarcodeScanning == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_GmsBarcodeScanning,
      &_m_GmsBarcodeScanning__getClient, "getClient", "(Landroid/content/Context;)Lcom/google/mlkit/vision/codescanner/GmsBarcodeScanner;");
    if (_m_GmsBarcodeScanning__getClient == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_GmsBarcodeScanning, _m_GmsBarcodeScanning__getClient, context);
    return to_global_ref_result(_result);
}

jmethodID _m_GmsBarcodeScanning__getClient1 = NULL;
FFI_PLUGIN_EXPORT
JniResult GmsBarcodeScanning__getClient1(jobject context,jobject gmsBarcodeScannerOptions) {
    load_env();
        load_class_global_ref(&_c_GmsBarcodeScanning, "com/google/mlkit/vision/codescanner/GmsBarcodeScanning");
    if (_c_GmsBarcodeScanning == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_GmsBarcodeScanning,
      &_m_GmsBarcodeScanning__getClient1, "getClient", "(Landroid/content/Context;Lcom/google/mlkit/vision/codescanner/GmsBarcodeScannerOptions;)Lcom/google/mlkit/vision/codescanner/GmsBarcodeScanner;");
    if (_m_GmsBarcodeScanning__getClient1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_GmsBarcodeScanning, _m_GmsBarcodeScanning__getClient1, context, gmsBarcodeScannerOptions);
    return to_global_ref_result(_result);
}

// com.google.mlkit.vision.codescanner.GmsBarcodeScanner
jclass _c_GmsBarcodeScanner = NULL;

jmethodID _m_GmsBarcodeScanner__startScan = NULL;
FFI_PLUGIN_EXPORT
JniResult GmsBarcodeScanner__startScan(jobject self_) {
    load_env();
        load_class_global_ref(&_c_GmsBarcodeScanner, "com/google/mlkit/vision/codescanner/GmsBarcodeScanner");
    if (_c_GmsBarcodeScanner == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_GmsBarcodeScanner,
      &_m_GmsBarcodeScanner__startScan, "startScan", "()Lcom/google/android/gms/tasks/Task;");
    if (_m_GmsBarcodeScanner__startScan == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_GmsBarcodeScanner__startScan);
    return to_global_ref_result(_result);
}

// com.google.mlkit.vision.barcode.common.Barcode
jclass _c_Barcode = NULL;

jmethodID _m_Barcode__getFormat = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getFormat(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getFormat, "getFormat", "()I");
    if (_m_Barcode__getFormat == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_Barcode__getFormat);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_Barcode__getValueType = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getValueType(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getValueType, "getValueType", "()I");
    if (_m_Barcode__getValueType == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_Barcode__getValueType);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_Barcode__getBoundingBox = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getBoundingBox(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getBoundingBox, "getBoundingBox", "()Landroid/graphics/Rect;");
    if (_m_Barcode__getBoundingBox == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getBoundingBox);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getCalendarEvent = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getCalendarEvent(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getCalendarEvent, "getCalendarEvent", "()Lcom/google/mlkit/vision/barcode/common/Barcode$CalendarEvent;");
    if (_m_Barcode__getCalendarEvent == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getCalendarEvent);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getContactInfo = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getContactInfo(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getContactInfo, "getContactInfo", "()Lcom/google/mlkit/vision/barcode/common/Barcode$ContactInfo;");
    if (_m_Barcode__getContactInfo == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getContactInfo);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getDriverLicense = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getDriverLicense(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getDriverLicense, "getDriverLicense", "()Lcom/google/mlkit/vision/barcode/common/Barcode$DriverLicense;");
    if (_m_Barcode__getDriverLicense == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getDriverLicense);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getEmail = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getEmail(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getEmail, "getEmail", "()Lcom/google/mlkit/vision/barcode/common/Barcode$Email;");
    if (_m_Barcode__getEmail == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getEmail);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getGeoPoint = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getGeoPoint(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getGeoPoint, "getGeoPoint", "()Lcom/google/mlkit/vision/barcode/common/Barcode$GeoPoint;");
    if (_m_Barcode__getGeoPoint == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getGeoPoint);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getPhone = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getPhone(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getPhone, "getPhone", "()Lcom/google/mlkit/vision/barcode/common/Barcode$Phone;");
    if (_m_Barcode__getPhone == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getPhone);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getSms = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getSms(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getSms, "getSms", "()Lcom/google/mlkit/vision/barcode/common/Barcode$Sms;");
    if (_m_Barcode__getSms == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getSms);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getUrl = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getUrl(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getUrl, "getUrl", "()Lcom/google/mlkit/vision/barcode/common/Barcode$UrlBookmark;");
    if (_m_Barcode__getUrl == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getUrl);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getWifi = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getWifi(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getWifi, "getWifi", "()Lcom/google/mlkit/vision/barcode/common/Barcode$WiFi;");
    if (_m_Barcode__getWifi == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getWifi);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getDisplayValue = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getDisplayValue(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getDisplayValue, "getDisplayValue", "()Ljava/lang/String;");
    if (_m_Barcode__getDisplayValue == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getDisplayValue);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getRawValue = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getRawValue(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getRawValue, "getRawValue", "()Ljava/lang/String;");
    if (_m_Barcode__getRawValue == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getRawValue);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__ctor = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__ctor(jobject barcodeSource) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__ctor, "<init>", "(Lcom/google/mlkit/vision/barcode/common/internal/BarcodeSource;)V");
    if (_m_Barcode__ctor == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Barcode, _m_Barcode__ctor, barcodeSource);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__ctor1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__ctor1(jobject barcodeSource,jobject matrix) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__ctor1, "<init>", "(Lcom/google/mlkit/vision/barcode/common/internal/BarcodeSource;Landroid/graphics/Matrix;)V");
    if (_m_Barcode__ctor1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Barcode, _m_Barcode__ctor1, barcodeSource, matrix);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getRawBytes = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getRawBytes(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getRawBytes, "getRawBytes", "()[B");
    if (_m_Barcode__getRawBytes == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getRawBytes);
    return to_global_ref_result(_result);
}

jmethodID _m_Barcode__getCornerPoints = NULL;
FFI_PLUGIN_EXPORT
JniResult Barcode__getCornerPoints(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Barcode, "com/google/mlkit/vision/barcode/common/Barcode");
    if (_c_Barcode == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Barcode,
      &_m_Barcode__getCornerPoints, "getCornerPoints", "()[Landroid/graphics/Point;");
    if (_m_Barcode__getCornerPoints == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Barcode__getCornerPoints);
    return to_global_ref_result(_result);
}

// com.google.mlkit.vision.barcode.common.internal.BarcodeSource
jclass _c_BarcodeSource = NULL;

jmethodID _m_BarcodeSource__getFormat = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getFormat(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getFormat, "getFormat", "()I");
    if (_m_BarcodeSource__getFormat == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_BarcodeSource__getFormat);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_BarcodeSource__getValueType = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getValueType(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getValueType, "getValueType", "()I");
    if (_m_BarcodeSource__getValueType == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_BarcodeSource__getValueType);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_BarcodeSource__getBoundingBox = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getBoundingBox(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getBoundingBox, "getBoundingBox", "()Landroid/graphics/Rect;");
    if (_m_BarcodeSource__getBoundingBox == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getBoundingBox);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getCalendarEvent = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getCalendarEvent(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getCalendarEvent, "getCalendarEvent", "()Lcom/google/mlkit/vision/barcode/common/Barcode$CalendarEvent;");
    if (_m_BarcodeSource__getCalendarEvent == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getCalendarEvent);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getContactInfo = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getContactInfo(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getContactInfo, "getContactInfo", "()Lcom/google/mlkit/vision/barcode/common/Barcode$ContactInfo;");
    if (_m_BarcodeSource__getContactInfo == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getContactInfo);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getDriverLicense = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getDriverLicense(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getDriverLicense, "getDriverLicense", "()Lcom/google/mlkit/vision/barcode/common/Barcode$DriverLicense;");
    if (_m_BarcodeSource__getDriverLicense == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getDriverLicense);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getEmail = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getEmail(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getEmail, "getEmail", "()Lcom/google/mlkit/vision/barcode/common/Barcode$Email;");
    if (_m_BarcodeSource__getEmail == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getEmail);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getGeoPoint = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getGeoPoint(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getGeoPoint, "getGeoPoint", "()Lcom/google/mlkit/vision/barcode/common/Barcode$GeoPoint;");
    if (_m_BarcodeSource__getGeoPoint == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getGeoPoint);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getPhone = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getPhone(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getPhone, "getPhone", "()Lcom/google/mlkit/vision/barcode/common/Barcode$Phone;");
    if (_m_BarcodeSource__getPhone == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getPhone);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getSms = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getSms(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getSms, "getSms", "()Lcom/google/mlkit/vision/barcode/common/Barcode$Sms;");
    if (_m_BarcodeSource__getSms == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getSms);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getUrl = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getUrl(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getUrl, "getUrl", "()Lcom/google/mlkit/vision/barcode/common/Barcode$UrlBookmark;");
    if (_m_BarcodeSource__getUrl == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getUrl);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getWifi = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getWifi(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getWifi, "getWifi", "()Lcom/google/mlkit/vision/barcode/common/Barcode$WiFi;");
    if (_m_BarcodeSource__getWifi == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getWifi);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getDisplayValue = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getDisplayValue(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getDisplayValue, "getDisplayValue", "()Ljava/lang/String;");
    if (_m_BarcodeSource__getDisplayValue == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getDisplayValue);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getRawValue = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getRawValue(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getRawValue, "getRawValue", "()Ljava/lang/String;");
    if (_m_BarcodeSource__getRawValue == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getRawValue);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getRawBytes = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getRawBytes(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getRawBytes, "getRawBytes", "()[B");
    if (_m_BarcodeSource__getRawBytes == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getRawBytes);
    return to_global_ref_result(_result);
}

jmethodID _m_BarcodeSource__getCornerPoints = NULL;
FFI_PLUGIN_EXPORT
JniResult BarcodeSource__getCornerPoints(jobject self_) {
    load_env();
        load_class_global_ref(&_c_BarcodeSource, "com/google/mlkit/vision/barcode/common/internal/BarcodeSource");
    if (_c_BarcodeSource == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_BarcodeSource,
      &_m_BarcodeSource__getCornerPoints, "getCornerPoints", "()[Landroid/graphics/Point;");
    if (_m_BarcodeSource__getCornerPoints == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_BarcodeSource__getCornerPoints);
    return to_global_ref_result(_result);
}

// com.google.android.gms.tasks.Task
jclass _c_Task = NULL;

jmethodID _m_Task__addOnCanceledListener = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnCanceledListener(jobject self_,jobject onCanceledListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnCanceledListener, "addOnCanceledListener", "(Lcom/google/android/gms/tasks/OnCanceledListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnCanceledListener == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnCanceledListener, onCanceledListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnCanceledListener1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnCanceledListener1(jobject self_,jobject activity,jobject onCanceledListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnCanceledListener1, "addOnCanceledListener", "(Landroid/app/Activity;Lcom/google/android/gms/tasks/OnCanceledListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnCanceledListener1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnCanceledListener1, activity, onCanceledListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnCanceledListener2 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnCanceledListener2(jobject self_,jobject executor,jobject onCanceledListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnCanceledListener2, "addOnCanceledListener", "(Ljava/util/concurrent/Executor;Lcom/google/android/gms/tasks/OnCanceledListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnCanceledListener2 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnCanceledListener2, executor, onCanceledListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnCompleteListener = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnCompleteListener(jobject self_,jobject onCompleteListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnCompleteListener, "addOnCompleteListener", "(Lcom/google/android/gms/tasks/OnCompleteListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnCompleteListener == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnCompleteListener, onCompleteListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnCompleteListener1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnCompleteListener1(jobject self_,jobject activity,jobject onCompleteListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnCompleteListener1, "addOnCompleteListener", "(Landroid/app/Activity;Lcom/google/android/gms/tasks/OnCompleteListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnCompleteListener1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnCompleteListener1, activity, onCompleteListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnCompleteListener2 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnCompleteListener2(jobject self_,jobject executor,jobject onCompleteListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnCompleteListener2, "addOnCompleteListener", "(Ljava/util/concurrent/Executor;Lcom/google/android/gms/tasks/OnCompleteListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnCompleteListener2 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnCompleteListener2, executor, onCompleteListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnFailureListener = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnFailureListener(jobject self_,jobject onFailureListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnFailureListener, "addOnFailureListener", "(Lcom/google/android/gms/tasks/OnFailureListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnFailureListener == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnFailureListener, onFailureListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnFailureListener1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnFailureListener1(jobject self_,jobject activity,jobject onFailureListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnFailureListener1, "addOnFailureListener", "(Landroid/app/Activity;Lcom/google/android/gms/tasks/OnFailureListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnFailureListener1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnFailureListener1, activity, onFailureListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnFailureListener2 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnFailureListener2(jobject self_,jobject executor,jobject onFailureListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnFailureListener2, "addOnFailureListener", "(Ljava/util/concurrent/Executor;Lcom/google/android/gms/tasks/OnFailureListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnFailureListener2 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnFailureListener2, executor, onFailureListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnSuccessListener = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnSuccessListener(jobject self_,jobject onSuccessListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnSuccessListener, "addOnSuccessListener", "(Lcom/google/android/gms/tasks/OnSuccessListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnSuccessListener == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnSuccessListener, onSuccessListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnSuccessListener1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnSuccessListener1(jobject self_,jobject activity,jobject onSuccessListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnSuccessListener1, "addOnSuccessListener", "(Landroid/app/Activity;Lcom/google/android/gms/tasks/OnSuccessListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnSuccessListener1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnSuccessListener1, activity, onSuccessListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__addOnSuccessListener2 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__addOnSuccessListener2(jobject self_,jobject executor,jobject onSuccessListener) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__addOnSuccessListener2, "addOnSuccessListener", "(Ljava/util/concurrent/Executor;Lcom/google/android/gms/tasks/OnSuccessListener;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__addOnSuccessListener2 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__addOnSuccessListener2, executor, onSuccessListener);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__continueWith = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__continueWith(jobject self_,jobject continuation) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__continueWith, "continueWith", "(Lcom/google/android/gms/tasks/Continuation;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__continueWith == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__continueWith, continuation);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__continueWith1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__continueWith1(jobject self_,jobject executor,jobject continuation) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__continueWith1, "continueWith", "(Ljava/util/concurrent/Executor;Lcom/google/android/gms/tasks/Continuation;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__continueWith1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__continueWith1, executor, continuation);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__continueWithTask = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__continueWithTask(jobject self_,jobject continuation) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__continueWithTask, "continueWithTask", "(Lcom/google/android/gms/tasks/Continuation;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__continueWithTask == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__continueWithTask, continuation);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__continueWithTask1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__continueWithTask1(jobject self_,jobject executor,jobject continuation) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__continueWithTask1, "continueWithTask", "(Ljava/util/concurrent/Executor;Lcom/google/android/gms/tasks/Continuation;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__continueWithTask1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__continueWithTask1, executor, continuation);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__onSuccessTask = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__onSuccessTask(jobject self_,jobject successContinuation) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__onSuccessTask, "onSuccessTask", "(Lcom/google/android/gms/tasks/SuccessContinuation;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__onSuccessTask == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__onSuccessTask, successContinuation);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__onSuccessTask1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__onSuccessTask1(jobject self_,jobject executor,jobject successContinuation) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__onSuccessTask1, "onSuccessTask", "(Ljava/util/concurrent/Executor;Lcom/google/android/gms/tasks/SuccessContinuation;)Lcom/google/android/gms/tasks/Task;");
    if (_m_Task__onSuccessTask1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__onSuccessTask1, executor, successContinuation);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__getException = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__getException(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__getException, "getException", "()Ljava/lang/Exception;");
    if (_m_Task__getException == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__getException);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__getResult = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__getResult(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__getResult, "getResult", "()Ljava/lang/Object;");
    if (_m_Task__getResult == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__getResult);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__getResult1 = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__getResult1(jobject self_,jobject class) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__getResult1, "getResult", "(Ljava/lang/Class;)Ljava/lang/Object;");
    if (_m_Task__getResult1 == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_Task__getResult1, class);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__ctor = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__ctor() {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__ctor, "<init>", "()V");
    if (_m_Task__ctor == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Task, _m_Task__ctor);
    return to_global_ref_result(_result);
}

jmethodID _m_Task__isCanceled = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__isCanceled(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__isCanceled, "isCanceled", "()Z");
    if (_m_Task__isCanceled == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    uint8_t _result = (*jniEnv)->CallBooleanMethod(jniEnv, self_, _m_Task__isCanceled);
    return (JniResult){.value = {.z = _result}, .exception = check_exception()};
}

jmethodID _m_Task__isComplete = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__isComplete(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__isComplete, "isComplete", "()Z");
    if (_m_Task__isComplete == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    uint8_t _result = (*jniEnv)->CallBooleanMethod(jniEnv, self_, _m_Task__isComplete);
    return (JniResult){.value = {.z = _result}, .exception = check_exception()};
}

jmethodID _m_Task__isSuccessful = NULL;
FFI_PLUGIN_EXPORT
JniResult Task__isSuccessful(jobject self_) {
    load_env();
        load_class_global_ref(&_c_Task, "com/google/android/gms/tasks/Task");
    if (_c_Task == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_Task,
      &_m_Task__isSuccessful, "isSuccessful", "()Z");
    if (_m_Task__isSuccessful == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    uint8_t _result = (*jniEnv)->CallBooleanMethod(jniEnv, self_, _m_Task__isSuccessful);
    return (JniResult){.value = {.z = _result}, .exception = check_exception()};
}

